apiVersion: batch/v1
kind: Job
metadata:
  name: crawl-js-apis
spec:
  parallelism: 8 # We have got 8 nodes available

  template:
    metadata:
      labels:
        app: crawl-js-apis

    spec:
      containers:
      - name: crawl-js-apis
        image: martan305/web_crawler:282bd2bb8dbd46ea1c8b9d40c7c69baafacdae00
        command: ["python",  "crawl-javascript-apis.py", "--browsers", "3", "--privacy"]
        imagePullPolicy: IfNotPresent

        volumeMounts:
          - mountPath: /opt/OpenWPM/datadir
            name: datadir

        env:
          - name: REDIS_URL
            valueFrom:
              configMapKeyRef:
                name: web-crawler
                key: REDIS_URL

      volumes:
        - name: datadir
          hostPath: 
            path: /home/web_crawler/datadir
            type: DirectoryOrCreate

      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                    - crawl-js-apis
              topologyKey: kubernetes.io/hostname

      restartPolicy: Never
  backoffLimit: 4
