name: Docker Image CI

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag martan305/web_crawler:$GITHUB_SHA
    - name: Login into dockerhub
      env:
        DOCKERHUB_LOGIN: ${{ secrets.DOCKERHUB_LOGIN }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: docker login -u $DOCKERHUB_LOGIN -p $DOCKERHUB_PASSWORD
    - name: Push image to dockerhub registry
      run: docker push martan305/web_crawler:$GITHUB_SHA
